version: "3.8"

services:
  spark-master:
    image: bitnami/spark:3.5
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
      SPARK_NO_DAEMONIZE: "true"
    ports:
      - "7077:7077"   # cluster
      - "8081:8080"   # UI master -> 8081 host
    volumes:
      - /srv/iac/spark/jobs:/opt/spark/jobs
      - /srv/iac/spark/conf:/opt/bitnami/spark/conf
    restart: unless-stopped

  spark-worker:
    image: bitnami/spark:3.5
    depends_on: [spark-master]
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 4G
      SPARK_WORKER_CORES: 2
    ports:
      - "8082:8081"   # UI worker -> 8082 host
    volumes:
      - /srv/iac/spark/jobs:/opt/spark/jobs
      - /srv/iac/spark/conf:/opt/bitnami/spark/conf
    restart: unless-stopped