---
- name: Create app directory
  file:
    path: /opt/app
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/app/docker-compose.yml
    mode: "0644"

- name: Pull & up
  shell: |
    docker compose -f /opt/app/docker-compose.yml pull
    docker compose -f /opt/app/docker-compose.yml up -d
  args: { executable: /bin/bash }
