stacks:
  - name: airflow
    endpoint: airflow
    repo_url: "git@github.com:infra-trade/infra.git"
    compose_path: "airflow/compose/docker-compose.yml"
    git_ref: "main"
    env:
      - { name: AIRFLOW_IMAGE, value: "apache/airflow:2.10.2" }
      - { name: AIRFLOW__CORE__EXECUTOR, value: "LocalExecutor" }
      - { name: PUID, value: "50000" }
      - { name: PG_HOST, value: "db-core" }
      # añade TODAS las ${VAR} que aparezcan en ese compose