# inventories/group_vars/all.yml
portainer_url: "https://10.20.0.12:9443"

# CE 2.33.2 usa X-API-Key (no JWT). Puedes guardar la API key aquí o pasarla por env/-e.
portainer_token: "{{ lookup('env','PORTAINER_TOKEN') | default('', true) }}"

# Mapa lógico -> endpointId (ajústalos a tus IDs reales)
endpoints:
  mon: 2
  airflow: 3
  kafka: 4
  spark: 5
  db: 6

# Stacks que quieres crear/actualizar desde Git
stacks:
  - name: mon
    endpoint: mon
    repo_url: "https://github.com/infra-trade/infra.git"
    compose_path: "mon/compose/docker-compose.yml"
    git_ref: "main"
    env: []

  - name: airflow
    endpoint: airflow
    repo_url: "https://github.com/infra-trade/infra.git"
    compose_path: "airflow/compose/docker-compose.yml"
    git_ref: "main"
    env: []

  - name: kafka
    endpoint: kafka
    repo_url: "https://github.com/infra-trade/infra.git"
    compose_path: "kafka/compose/docker-compose.yml"
    git_ref: "main"
    env: []

  - name: spark
    endpoint: spark
    repo_url: "https://github.com/infra-trade/infra.git"
    compose_path: "spark/compose/docker-compose.yml"
    git_ref: "main"
    env: []

  - name: db
    endpoint: db
    repo_url: "https://github.com/infra-trade/infra.git"
    compose_path: "db/compose/docker-compose.yml"
    git_ref: "main"
    env: []