portainer_url: "https://10.20.0.12:9443"

# Mapa de endpoints (IDs reales de tus agentes/servidores en Portainer)
endpoints:
  mon: 2
  airflow: 2
  kafka: 2
  spark: 2
  db: 2

git_default_ref: "main"