# URL y endpoint mapping
portainer_url: "https://10.20.0.12:9443"

# Si quieres que tome el token del entorno, déjalo vacío y exporta PORTAINER_TOKEN al ejecutar
portainer_api_token: "ptr_rknyH3kGh9y4UTdtpFAcDF41DVO3jz3/HRQsQ+BPJ/k="

# Mapea tus endpoints (nombres -> ID del endpoint en Portainer)
endpoints:
  mon: 2

# Por defecto, credenciales de Git para repos privados (HTTPS)
github_username: "infra-trade"
# Ojo: github_pat debe ir cifrado en el vault. Aquí solo referencia.