---
- name: Expandir discos (scsi0) en Proxmox para las VMs objetivo
  hosts: localhost
  gather_facts: false

  vars:
    pve_ssh_host: "192.168.100.100"  # Host/IP del Proxmox (SSH)
    # Catálogo mínimo (solo necesitamos vmid)
    vms:
      airflow-core: { vmid: 9301 }
      kafka-core:   { vmid: 9302 }
      spark-core:   { vmid: 9303 }
      db-core:      { vmid: 9304 }
      mon-core:     { vmid: 9305 }

    # Crecimiento por VM (en GB). Si no está definido, usa grow_by_default_gb.
    grow_by_default_gb: 40
    grow_by_map:
      airflow-core: 40
      kafka-core:   40
      spark-core:   40
      db-core:      40
      mon-core:     40

  tasks:
    - name: Construir lista (dict -> items)
      set_fact:
        vmlist: "{{ vms | dict2items }}"

    - name: qm resize scsi0 +XG (puede ser en caliente con scsi/lvm-thin/qcow2)
      become: true
      delegate_to: "{{ pve_ssh_host }}"
      ansible.builtin.command:
        cmd: >
          qm resize {{ item.value.vmid }} scsi0 +{{ grow_by_map.get(item.key, grow_by_default_gb) }}G
      register: qmresize_out
      loop: "{{ vmlist }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Resultado de resize
      debug:
        var: qmresize_out.results | map(attribute='stdout') | list