---
msg:
- "Portainer listo:"
- " https://{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}:{{ portainer_https_port }}"
- " http://{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}:{{ portainer_http_port }} (opcional)"
- "Si es el primer arranque, crea el usuario admin al acceder."
tags: [portainer_server]




- name: Deploy/Upgrade Portainer Agent on all agent nodes
hosts: agent_nodes
become: true
gather_facts: false
collections:
- community.docker
vars:
agent_image: "{{ agent_image | default('portainer/agent:2.21.5') }}"
agent_port: 9001
allow_from: "" # Si usas UFW, IP/32 del server
tasks:
- name: Ensure Docker is installed (sanity)
command: docker --version
register: docker_v
changed_when: false
failed_when: docker_v.rc != 0
tags: [portainer_agent]


- name: Pull pinned agent image
community.docker.docker_image:
name: "{{ agent_image }}"
source: pull
tags: [portainer_agent]


- name: Ensure agent container is running (recreate on image change)
community.docker.docker_container:
name: portainer_agent
image: "{{ agent_image }}"
restart_policy: unless-stopped
recreate: true
pull: true
state: started
published_ports:
- "{{ agent_port }}:9001"
volumes:
- /var/run/docker.sock:/var/run/docker.sock
- /var/lib/docker/volumes:/var/lib/docker/volumes
tags: [portainer_agent]


- name: Check if UFW is present
command: ufw status
register: ufw_status
changed_when: false
failed_when: false
tags: [portainer_agent, firewall]


- name: Ensure rule for 9001 from monitor (optional)
when: ufw_status.rc == 0 and allow_from | length > 0
shell: |
set -e
ufw status | grep -q "{{ agent_port }}/tcp" | grep -q "{{ allow_from }}" || ufw allow from {{ allow_from }} to any port {{ agent_port }} proto tcp
ufw reload
args:
warn: false
changed_when: false
failed_when: false
tags: [portainer_agent, firewall]


- name: Show agent endpoint
debug:
msg:
- "Agent listo en {{ inventory_hostname }}: {{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}:{{ agent_port }}"
tags: [portainer_agent]