---
- name: Deploy/upgrade Portainer Agent (always latest)
  hosts: agent_nodes
  become: true
  gather_facts: false

  collections:
    - community.docker

  vars:
    agent_image: "portainer/agent:latest"   # <- siempre la última
    agent_port: 9001

  tasks:
    - name: Pull latest agent image
      community.docker.docker_image:
        name: "{{ agent_image }}"
        source: pull

    - name: Ensure agent container is running (recreate on image change)
      community.docker.docker_container:
        name: portainer_agent
        image: "{{ agent_image }}"
        published_ports:
          - "{{ agent_port }}:9001"
        restart_policy: unless-stopped
        recreate: true
        pull: true
        state: started
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes