---
- name: Deploy Portainer Agent (Compose) on all agent nodes
  hosts: agent_nodes
  become: true
  gather_facts: false

  vars:
    agent_dir: /opt/portainer-agent
    agent_compose: /opt/portainer-agent/docker-compose.yml
    agent_port: 9001              # Portainer Server se conecta a este puerto en cada node
    allow_from: ""                # opcional: IP/32 de mon-core para firewall (ej. "10.20.0.12/32")

  tasks:
    - name: Ensure Docker is installed (sanity check)
      command: docker --version
      register: docker_v
      changed_when: false
      failed_when: docker_v.rc != 0

    - name: Ensure agent directory exists
      file:
        path: "{{ agent_dir }}"
        state: directory
        mode: "0755"

    - name: Write docker-compose for Portainer Agent
      copy:
        dest: "{{ agent_compose }}"
        mode: "0644"
        content: |
          services:
            agent:
              image: portainer/agent:2.21.4
              container_name: portainer_agent
              restart: unless-stopped
              environment:
                AGENT_CLUSTER_ADDR: tasks.agent
                LOG_LEVEL: INFO
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - /var/lib/docker/volumes:/var/lib/docker/volumes
              ports:
                - "{{ agent_port }}:9001"
              deploy:
                mode: global
          networks: {}
          volumes: {}

    - name: Bring up Portainer Agent
      shell: docker compose -f {{ agent_compose }} up -d
      args:
        chdir: "{{ agent_dir }}"

    # (Opcional) Abrir puerto 9001 solo desde mon-core si existe UFW
    - name: Check if UFW is present
      command: ufw status
      register: ufw_status
      changed_when: false
      failed_when: false

    - name: Allow 9001 from mon-core via UFW (optional)
      when: ufw_status.rc == 0 and allow_from | length > 0
      shell: |
        set -e
        ufw allow from {{ allow_from }} to any port {{ agent_port }} proto tcp
        ufw reload
      args:
        warn: false
      changed_when: false
      failed_when: false

    - name: Show agent endpoint
      debug:
        msg:
          - "Agent listo en {{ inventory_hostname }}: {{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}:{{ agent_port }}"