---
- name: Patch all VMs + enable NTP + set timezone (CR)
  hosts: core_vms
  become: true
  gather_facts: false

  vars:
    tz_name: "America/Costa_Rica"
    ntp_servers:
      - "time.cloudflare.com"
      - "time.google.com"
      - "0.pool.ntp.org"
      - "1.pool.ntp.org"
    apt_retries: 3
    apt_delay: 5
    enable_unattended_upgrades: true

  pre_tasks:
    - name: Ensure minimal tools present
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - systemd-timesyncd
          - unattended-upgrades
        state: present
        update_cache: yes
      register: prepkgs

    - name: Force APT IPv4 to avoid odd networks (idempotent)
      copy:
        dest: /etc/apt/apt.conf.d/99force-ipv4
        mode: "0644"
        content: |
          Acquire::ForceIPv4 "true";
      notify: apt-clean

  tasks:
    # -------- TIME ----------
    - name: Set timezone to Costa Rica
      command: timedatectl set-timezone {{ tz_name }}
      changed_when: false

    - name: Configure systemd-timesyncd with custom NTP pool
      copy:
        dest: /etc/systemd/timesyncd.conf
        mode: "0644"
        content: |
          [Time]
          NTP={{ ntp_servers | join(' ') }}
          FallbackNTP=2.pool.ntp.org 3.pool.ntp.org
      notify: restart-timesyncd

    - name: Ensure NTP via systemd-timesyncd is enabled
      command: timedatectl set-ntp true
      changed_when: false

    # -------- PATCHING ----------
    - name: apt-get update (with retries)
      apt:
        update_cache: yes
      register: aptupd
      retries: "{{ apt_retries }}"
      delay: "{{ apt_delay }}"
      until: aptupd is succeeded

    - name: Full upgrade (security + kernel)
      apt:
        upgrade: dist
      register: full_upg

    - name: Autoremove & autoclean
      apt:
        autoremove: yes
        autoclean: yes

    # -------- OPTIONAL: unattended-upgrades ----------
    - name: Enable unattended-upgrades (optional)
      when: enable_unattended_upgrades
      block:
        - name: Ensure unattended-upgrades service enabled
          systemd:
            name: unattended-upgrades
            enabled: true
            state: started

        - name: Enable periodic APT updates & unattended upgrades
          copy:
            dest: /etc/apt/apt.conf.d/20auto-upgrades
            mode: "0644"
            content: |
              APT::Periodic::Update-Package-Lists "1";
              APT::Periodic::Download-Upgradeable-Packages "1";
              APT::Periodic::AutocleanInterval "7";
              APT::Periodic::Unattended-Upgrade "1";

    # -------- REBOOT IF NEEDED ----------
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if kernel or core libs were updated
      reboot:
        msg: "Reboot triggered by Ansible after patching"
        reboot_timeout: 1200
      when: reboot_required.stat.exists

    # -------- VERIFY ----------
    - name: Show time sync status (quick)
      shell: |
        set -eo pipefail
        timedatectl
      args:
        executable: /bin/bash
      register: tdctl
      changed_when: false

    - name: Debug time status
      debug:
        var: tdctl.stdout_lines

  handlers:
    - name: restart-timesyncd
      systemd:
        name: systemd-timesyncd
        state: restarted
        enabled: true

    - name: apt-clean
      shell: |
        set -e
        rm -f /var/lib/apt/lists/lock /var/lib/dpkg/lock /var/cache/apt/archives/lock || true
        apt-get clean || true
      args:
        executable: /bin/bash
      changed_when: false