---
- name: Upgrade Portainer (Server + Agents) to latest
  hosts: monitor:agent_nodes
  gather_facts: false
  become: true

  tasks:
    - meta: include_playbook
      vars:
        _dummy: true
      file: 31_setup_portainer_mon.yml
      when: "'monitor' in group_names"

    - meta: include_playbook
      vars:
        _dummy: true
      file: 32_setup_portainer_agents.yml
      when: "'agent_nodes' in group_names"