---
- name: Sync de artefactos (DAGs Airflow, configs Kafka, jobs Spark)
  hosts: "{{ targets | default(sync_target_group) }}"
  become: true
  vars:
    ensure_dirs:
      - "{{ sync_map.airflow.dest_dags }}"
      - "{{ sync_map.airflow.dest_plugins }}"
      - "{{ sync_map.kafka.dest_config }}"
      - "{{ sync_map.kafka.dest_scripts }}"
      - "{{ sync_map.spark.dest_jobs }}"
      - "{{ sync_map.spark.dest_conf }}"
  pre_tasks:
    - name: Asegurar rsync si prefer_rsync=true (solo Debian/Ubuntu)
      ansible.builtin.package:
        name: rsync
        state: present
      when: prefer_rsync | bool
      ignore_errors: true

    - name: Crear árboles destino
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0775"
      loop: "{{ ensure_dirs }}"

    - name: Permisos (Airflow)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: true
        owner: "{{ sync_map.airflow.uid }}"
        group: "{{ sync_map.airflow.gid }}"
      loop:
        - "{{ sync_map.airflow.dest_dags }}"
        - "{{ sync_map.airflow.dest_plugins }}"
      when: sync_map.airflow is defined

    - name: Permisos (Kafka)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: true
        owner: "{{ sync_map.kafka.uid }}"
        group: "{{ sync_map.kafka.gid }}"
      loop:
        - "{{ sync_map.kafka.dest_config }}"
        - "{{ sync_map.kafka.dest_scripts }}"
      when: sync_map.kafka is defined

    - name: Permisos (Spark)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: true
        owner: "{{ sync_map.spark.uid }}"
        group: "{{ sync_map.spark.gid }}"
      loop:
        - "{{ sync_map.spark.dest_jobs }}"
        - "{{ sync_map.spark.dest_conf }}"
      when: sync_map.spark is defined

  tasks:
    # ========== AIRFLOW ==========
    - name: Sync Airflow DAGs (rsync)
      ansible.posix.synchronize:
        src: "{{ sync_map.airflow.src_dags }}/"
        dest: "{{ sync_map.airflow.dest_dags }}/"
        delete: false
        recursive: true
      delegate_to: localhost
      when:
        - sync_map.airflow is defined
        - prefer_rsync | bool
        - sync_map.airflow.src_dags is exists

    - name: Sync Airflow DAGs (fallback copy)
      ansible.builtin.copy:
        src: "{{ sync_map.airflow.src_dags }}/"
        dest: "{{ sync_map.airflow.dest_dags }}/"
        mode: "0644"
      when:
        - sync_map.airflow is defined
        - not prefer_rsync | bool
        - sync_map.airflow.src_dags is exists

    - name: Sync Airflow plugins (rsync)
      ansible.posix.synchronize:
        src: "{{ sync_map.airflow.src_plugins }}/"
        dest: "{{ sync_map.airflow.dest_plugins }}/"
        delete: false
        recursive: true
      delegate_to: localhost
      when:
        - sync_map.airflow is defined
        - prefer_rsync | bool
        - sync_map.airflow.src_plugins is exists

    - name: Sync Airflow plugins (fallback copy)
      ansible.builtin.copy:
        src: "{{ sync_map.airflow.src_plugins }}/"
        dest: "{{ sync_map.airflow.dest_plugins }}/"
        mode: "0644"
      when:
        - sync_map.airflow is defined
        - not prefer_rsync | bool
        - sync_map.airflow.src_plugins is exists

    # ========== KAFKA ==========
    - name: Sync Kafka config (rsync)
      ansible.posix.synchronize:
        src: "{{ sync_map.kafka.src_config }}/"
        dest: "{{ sync_map.kafka.dest_config }}/"
        recursive: true
      delegate_to: localhost
      when:
        - sync_map.kafka is defined
        - prefer_rsync | bool
        - sync_map.kafka.src_config is exists

    - name: Sync Kafka config (fallback copy)
      ansible.builtin.copy:
        src: "{{ sync_map.kafka.src_config }}/"
        dest: "{{ sync_map.kafka.dest_config }}/"
        mode: "0644"
      when:
        - sync_map.kafka is defined
        - not prefer_rsync | bool
        - sync_map.kafka.src_config is exists

    - name: Sync Kafka scripts (rsync)
      ansible.posix.synchronize:
        src: "{{ sync_map.kafka.src_scripts }}/"
        dest: "{{ sync_map.kafka.dest_scripts }}/"
        recursive: true
      delegate_to: localhost
      when:
        - sync_map.kafka is defined
        - prefer_rsync | bool
        - sync_map.kafka.src_scripts is exists

    - name: Sync Kafka scripts (fallback copy)
      ansible.builtin.copy:
        src: "{{ sync_map.kafka.src_scripts }}/"
        dest: "{{ sync_map.kafka.dest_scripts }}/"
        mode: "0755"
      when:
        - sync_map.kafka is defined
        - not prefer_rsync | bool
        - sync_map.kafka.src_scripts is exists

    # ========== SPARK ==========
    - name: Sync Spark jobs (rsync)
      ansible.posix.synchronize:
        src: "{{ sync_map.spark.src_jobs }}/"
        dest: "{{ sync_map.spark.dest_jobs }}/"
        recursive: true
      delegate_to: localhost
      when:
        - sync_map.spark is defined
        - prefer_rsync | bool
        - sync_map.spark.src_jobs is exists

    - name: Sync Spark jobs (fallback copy)
      ansible.builtin.copy:
        src: "{{ sync_map.spark.src_jobs }}/"
        dest: "{{ sync_map.spark.dest_jobs }}/"
        mode: "0644"
      when:
        - sync_map.spark is defined
        - not prefer_rsync | bool
        - sync_map.spark.src_jobs is exists

    - name: Sync Spark conf (rsync)
      ansible.posix.synchronize:
        src: "{{ sync_map.spark.src_conf }}/"
        dest: "{{ sync_map.spark.dest_conf }}/"
        recursive: true
      delegate_to: localhost
      when:
        - sync_map.spark is defined
        - prefer_rsync | bool
        - sync_map.spark.src_conf is exists

    - name: Sync Spark conf (fallback copy)
      ansible.builtin.copy:
        src: "{{ sync_map.spark.src_conf }}/"
        dest: "{{ sync_map.spark.dest_conf }}/"
        mode: "0644"
      when:
        - sync_map.spark is defined
        - not prefer_rsync | bool
        - sync_map.spark.src_conf is exists

  post_tasks:
    - name: Listado final de destinos
      ansible.builtin.shell: |
        set -e
        echo "AIRFLOW DAGS:";    ls -la {{ sync_map.airflow.dest_dags }} || true
        echo "AIRFLOW plugins:"; ls -la {{ sync_map.airflow.dest_plugins }} || true
        echo "KAFKA config:";    ls -la {{ sync_map.kafka.dest_config }} || true
        echo "KAFKA scripts:";   ls -la {{ sync_map.kafka.dest_scripts }} || true
        echo "SPARK jobs:";      ls -la {{ sync_map.spark.dest_jobs }} || true
        echo "SPARK conf:";      ls -la {{ sync_map.spark.dest_conf }} || true
      args:
        executable: /bin/bash
      register: listout
      changed_when: false

    - ansible.builtin.debug:
        var: listout.stdout_lines