---
dest: "{{ sync_map.spark.dest_jobs }}/"
mode: "0644"
when:
- sync_map.spark is defined
- (not prefer_rsync | bool)
- st_spark_jobs is defined and st_spark_jobs.stat.exists


- name: Sync Spark conf (rsync)
ansible.posix.synchronize:
src: "{{ sync_map.spark.src_conf }}/"
dest: "{{ sync_map.spark.dest_conf }}/"
recursive: true
delete: "{{ delete_policy.spark_conf | default(false) }}"
delegate_to: localhost
when:
- sync_map.spark is defined
- prefer_rsync | bool
- st_spark_conf is defined and st_spark_conf.stat.exists


- name: Sync Spark conf (fallback copy)
ansible.builtin.copy:
src: "{{ sync_map.spark.src_conf }}/"
dest: "{{ sync_map.spark.dest_conf }}/"
mode: "0644"
when:
- sync_map.spark is defined
- (not prefer_rsync | bool)
- st_spark_conf is defined and st_spark_conf.stat.exists


post_tasks:
- name: Listado final de destinos
ansible.builtin.shell: |
set -e
echo "AIRFLOW DAGS:"; ls -la {{ sync_map.airflow.dest_dags | default('/dev/null') }} || true
echo "AIRFLOW plugins:"; ls -la {{ sync_map.airflow.dest_plugins | default('/dev/null') }} || true
echo "KAFKA config:"; ls -la {{ sync_map.kafka.dest_config | default('/dev/null') }} || true
echo "KAFKA scripts:"; ls -la {{ sync_map.kafka.dest_scripts | default('/dev/null') }} || true
echo "SPARK jobs:"; ls -la {{ sync_map.spark.dest_jobs | default('/dev/null') }} || true
echo "SPARK conf:"; ls -la {{ sync_map.spark.dest_conf | default('/dev/null') }} || true
args:
executable: /bin/bash
register: listout
changed_when: false


- ansible.builtin.debug:
var: listout.stdout_lines


- name: Sync de artefactos (configs Prometheus, DAGs, etc.)
hosts: all
gather_facts: false
become: true
vars:
prefer_rsync: true
tasks:
- name: Crear destino conf Prometheus (si existe sync_map.mon)
when: hostvars[inventory_hostname].inventory_hostname == "mon-core" and (sync_map.mon is defined)
file:
path: "{{ sync_map.mon.dest_prom_conf }}"
state: directory
owner: "{{ sync_map.mon.uid | default(0) }}"
group: "{{ sync_map.mon.gid | default(0) }}"
mode: "0755"


- name: Sincronizar conf Prometheus (rsync si disponible)
when: hostvars[inventory_hostname].inventory_hostname == "mon-core" and (sync_map.mon is defined)
block:
- name: Con rsync
synchronize:
src: "{{ sync_map.mon.src_prom_conf }}/"
dest: "{{ sync_map.mon.dest_prom_conf }}/"
rsync_opts:
- "--delete"
delegate_to: localhost
when: prefer_rsync | bool


- name: Sin rsync (fallback)
copy:
src: "{{ sync_map.mon.src_prom_conf }}/"
dest: "{{ sync_map.mon.dest_prom_conf }}/"
owner: "{{ sync_map.mon.uid | default(0) }}"
group: "{{ sync_map.mon.gid | default(0) }}"
mode: "0644"
when: not prefer_rsync | bool