---
- name: Stop VM (best effort)
  community.proxmox.proxmox_kvm:
    api_host: "{{ pm_api_host }}"
    api_user: "{{ pm_api_user }}"
    api_token_id: "{{ pm_api_token_id }}"
    api_token_secret: "{{ pm_api_token_secret }}"
    validate_certs: "{{ validate_certs }}"
    node: "{{ pm_node }}"
    vmid: "{{ item.value.vmid }}"
    state: stopped
  failed_when: false

- name: Delete VM
  community.proxmox.proxmox_kvm:
    api_host: "{{ pm_api_host }}"
    api_user: "{{ pm_api_user }}"
    api_token_id: "{{ pm_api_token_id }}"
    api_token_secret: "{{ pm_api_token_secret }}"
    validate_certs: "{{ validate_certs }}"
    node: "{{ pm_node }}"
    vmid: "{{ item.value.vmid }}"
    state: absent
    purge: true
    force: true
  failed_when: false
