# ---- Portainer (CE 2.33.2) ----
portainer_url: "https://10.20.0.12:9443"
portainer_token: ""   # usa variable de entorno mejor

# Mapa Name -> EndpointId (pon tus IDs reales)
endpoints:
  mon: 2
  airflow: 3
  kafka: 4
  spark: 5
  db: 6