version: "3.8"

services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - /srv/iac/airflow/redis:/data
    restart: unless-stopped

  airflow-webserver:
    image: apache/airflow:2.9.3
    command: webserver
    env_file: .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@${AIRFLOW_DB_HOST}:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    ports:
      - "8081:8080"
    depends_on:
      - redis
    volumes:
      - /srv/iac/airflow/dags:/opt/airflow/dags
      - /srv/iac/airflow/plugins:/opt/airflow/plugins
      - /srv/iac/airflow/logs:/opt/airflow/logs
    user: "50000:50000"
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.9.3
    command: scheduler
    env_file: .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@${AIRFLOW_DB_HOST}:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - /srv/iac/airflow/dags:/opt/airflow/dags
      - /srv/iac/airflow/plugins:/opt/airflow/plugins
      - /srv/iac/airflow/logs:/opt/airflow/logs
    user: "50000:50000"
    restart: unless-stopped