---
# Requiere vars del item: st.name, st.endpoint, st.repo_url, st.compose_path, st.git_ref, st.env
# Requiere vars del play: portainer_url, portainer_api_token, endpoints (mapa), portainer_validate_certs

- name: Resolver endpointId para {{ st.name }}
  ansible.builtin.set_fact:
    _endpoint_id: "{{ (endpoints[st.endpoint] | default(omit)) | int }}"

- name: Validar endpointId mapeado
  ansible.builtin.assert:
    that:
      - _endpoint_id is defined
    fail_msg: "No encuentro endpointId para '{{ st.endpoint }}' en 'endpoints: {}'"
    success_msg: "endpointId = {{ _endpoint_id }}"

# 1) Listar stacks existentes y buscar uno por nombre+endpoint
- name: Listar stacks existentes (Portainer)
  ansible.builtin.uri:
    url: "{{ portainer_url }}/api/stacks"
    method: GET
    headers:
      X-API-Key: "{{ portainer_api_token }}"
    validate_certs: "{{ portainer_validate_certs }}"
    return_content: true
    status_code: 200
  register: _stacks_list

- name: Calcular lista de coincidencias
  ansible.builtin.set_fact:
    _matches: >-
      {{
        _stacks_list.json
        | selectattr('Name','equalto', st.name)
        | selectattr('EndpointId','equalto', (_endpoint_id | int))
        | list
      }}

- name: Derivar flags de existencia y stack existente
  ansible.builtin.set_fact:
    _exists: "{{ (_matches | length) > 0 }}"
    _existing_stack: "{{ _matches[0] if ((_matches | length) > 0) else omit }}"

- name: Debug match
  ansible.builtin.debug:
    msg:
      - "Stack '{{ st.name }}' en endpoint {{ _endpoint_id }} => {{ 'EXISTE' if _exists else 'NO EXISTE' }}"

# 2) Crear si NO existe: type=2 (compose), method=repository (desde Git)
# Nota: En CE 2.33.2, Portainer API puede responder 405 para creación desde Git.
# Si ves 405, esa feature no está disponible en tu edición/config y debes usar 35_deploy_stacks_compose.yml.
- name: Crear stack (si NO existe)
  ansible.builtin.uri:
    url: "{{ portainer_url }}/api/stacks?type=2&method=repository&endpointId={{ _endpoint_id }}"
    method: POST
    headers:
      X-API-Key: "{{ portainer_api_token }}"
      Content-Type: "application/json"
    validate_certs: "{{ portainer_validate_certs }}"
    body_format: json
    body:
      Name: "{{ st.name }}"
      RepositoryURL: "{{ st.repo_url }}"
      RepositoryReferenceName: "{{ st.git_ref | default('main') }}"
      ComposeFilePathInRepository: "{{ st.compose_path }}"
      RepositoryAuthentication: false
      Env: "{{ st.env | default([]) }}"
    status_code: [200, 201]
  register: _create_resp
  when: not _exists
  changed_when: true

# 3) Actualizar si existe: PUT /api/stacks/{id}?endpointId=...
- name: Actualizar stack (si EXISTE)
  ansible.builtin.uri:
    url: "{{ portainer_url }}/api/stacks/{{ _existing_stack.Id }}?endpointId={{ _endpoint_id }}"
    method: PUT
    headers:
      X-API-Key: "{{ portainer_api_token }}"
      Content-Type: "application/json"
    validate_certs: "{{ portainer_validate_certs }}"
    body_format: json
    body:
      Prune: true
      PullImage: true
      RepositoryAuthentication: false
      RepositoryReferenceName: "{{ st.git_ref | default('main') }}"
      Env: "{{ st.env | default([]) }}"
    status_code: 200
  register: _update_resp
  when: _exists
  changed_when: true